// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_stats.sql

package sqlcdb

import (
	"context"
)

const banUser = `-- name: BanUser :exec
UPDATE users SET is_banned = TRUE, updated_at = NOW() WHERE telegram_id = $1
`

func (q *Queries) BanUser(ctx context.Context, telegramID int64) error {
	_, err := q.db.Exec(ctx, banUser, telegramID)
	return err
}

const countActiveKeys = `-- name: CountActiveKeys :one
SELECT COUNT(*) FROM api_keys WHERE is_active = TRUE
`

func (q *Queries) CountActiveKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one

SELECT COUNT(*) FROM users
`

// Queries for admin dashboard stats. Phase 08: read-only aggregates used by AdminService.Stats.
// All queries are point-in-time reads; no writes here.
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersBanned = `-- name: CountUsersBanned :one
SELECT COUNT(*) FROM users WHERE is_banned = TRUE
`

func (q *Queries) CountUsersBanned(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersBanned)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersTrialUsed = `-- name: CountUsersTrialUsed :one
SELECT COUNT(*) FROM users WHERE trial_used = TRUE
`

func (q *Queries) CountUsersTrialUsed(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersTrialUsed)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersVerified = `-- name: CountUsersVerified :one
SELECT COUNT(*) FROM users WHERE is_verified = TRUE
`

func (q *Queries) CountUsersVerified(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersVerified)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const creditsOutstanding = `-- name: CreditsOutstanding :one
SELECT COALESCE(SUM(premium_credits),0)::bigint AS premium, COALESCE(SUM(standard_credits),0)::bigint AS standard FROM wallets
`

type CreditsOutstandingRow struct {
	Premium  int64 `json:"premium"`
	Standard int64 `json:"standard"`
}

func (q *Queries) CreditsOutstanding(ctx context.Context) (CreditsOutstandingRow, error) {
	row := q.db.QueryRow(ctx, creditsOutstanding)
	var i CreditsOutstandingRow
	err := row.Scan(&i.Premium, &i.Standard)
	return i, err
}

const getUserByKeyPrefix = `-- name: GetUserByKeyPrefix :one
SELECT u.id, u.telegram_id, u.telegram_username, u.phone_e164, u.is_verified, u.is_banned, u.trial_used, u.language, u.referred_by, u.created_at, u.updated_at, u.last_active_at FROM users u JOIN api_keys k ON k.user_id = u.id
WHERE k.key_prefix = $1 AND k.is_active = TRUE LIMIT 1
`

func (q *Queries) GetUserByKeyPrefix(ctx context.Context, keyPrefix string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByKeyPrefix, keyPrefix)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.PhoneE164,
		&i.IsVerified,
		&i.IsBanned,
		&i.TrialUsed,
		&i.Language,
		&i.ReferredBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, telegram_id, telegram_username, phone_e164, is_verified, is_banned, trial_used, language, referred_by, created_at, updated_at, last_active_at FROM users WHERE phone_e164 = $1 LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneE164 *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phoneE164)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.PhoneE164,
		&i.IsVerified,
		&i.IsBanned,
		&i.TrialUsed,
		&i.Language,
		&i.ReferredBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const txStats24h = `-- name: TxStats24h :one
SELECT
  COALESCE(SUM(amount_vnd) FILTER (WHERE status='paid' AND paid_at > NOW() - INTERVAL '24 hours'), 0)::bigint AS revenue_24h,
  COUNT(*) FILTER (WHERE status='paid' AND paid_at > NOW() - INTERVAL '24 hours') AS paid_24h,
  COUNT(*) FILTER (WHERE status='pending') AS pending,
  COUNT(*) FILTER (WHERE status='manual_review') AS manual_review
FROM transactions
`

type TxStats24hRow struct {
	Revenue24h   int64 `json:"revenue_24h"`
	Paid24h      int64 `json:"paid_24h"`
	Pending      int64 `json:"pending"`
	ManualReview int64 `json:"manual_review"`
}

func (q *Queries) TxStats24h(ctx context.Context) (TxStats24hRow, error) {
	row := q.db.QueryRow(ctx, txStats24h)
	var i TxStats24hRow
	err := row.Scan(
		&i.Revenue24h,
		&i.Paid24h,
		&i.Pending,
		&i.ManualReview,
	)
	return i, err
}

const unbanUser = `-- name: UnbanUser :exec
UPDATE users SET is_banned = FALSE, updated_at = NOW() WHERE telegram_id = $1
`

func (q *Queries) UnbanUser(ctx context.Context, telegramID int64) error {
	_, err := q.db.Exec(ctx, unbanUser, telegramID)
	return err
}
