// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAuditLogByEventSince = `-- name: CountAuditLogByEventSince :one
SELECT COUNT(*) FROM audit_log WHERE event = $1 AND created_at > $2
`

type CountAuditLogByEventSinceParams struct {
	Event     string    `json:"event"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CountAuditLogByEventSince(ctx context.Context, arg CountAuditLogByEventSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogByEventSince, arg.Event, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAuditLogByEventSince = `-- name: GetAuditLogByEventSince :many
SELECT id, user_id, key_id, event, ip_hash, country, metadata, created_at FROM audit_log WHERE event = $1 AND created_at > $2
ORDER BY created_at DESC LIMIT $3
`

type GetAuditLogByEventSinceParams struct {
	Event     string    `json:"event"`
	CreatedAt time.Time `json:"created_at"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) GetAuditLogByEventSince(ctx context.Context, arg GetAuditLogByEventSinceParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogByEventSince, arg.Event, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KeyID,
			&i.Event,
			&i.IpHash,
			&i.Country,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditLog = `-- name: InsertAuditLog :one

INSERT INTO audit_log (user_id, key_id, event, ip_hash, country, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, key_id, event, ip_hash, country, metadata, created_at
`

type InsertAuditLogParams struct {
	UserID   *uuid.UUID `json:"user_id"`
	KeyID    *uuid.UUID `json:"key_id"`
	Event    string     `json:"event"`
	IpHash   []byte     `json:"ip_hash"`
	Country  *string    `json:"country"`
	Metadata []byte     `json:"metadata"`
}

// Queries for the audit_log table. Phase 08: real event insert + lookup queries.
// ip_hash stores sha256(ip) — raw IP is never persisted.
// Phase 2 placeholder removed and replaced with real queries below.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.UserID,
		arg.KeyID,
		arg.Event,
		arg.IpHash,
		arg.Country,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyID,
		&i.Event,
		&i.IpHash,
		&i.Country,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
