// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcdb

import (
	"context"
)

const placeholderAuditSelect = `-- name: PlaceholderAuditSelect :one

SELECT 1 AS dummy
`

// Queries for the audit_log and safeguard_hits tables.
// Phase 2+ will add real queries here (event insert, anomaly lookup).
// ip_hash stores sha256(ip) — raw IP is never persisted (see docs/threat-model.md Phase 7).
// Placeholder kept so sqlc can parse this file without errors.
func (q *Queries) PlaceholderAuditSelect(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, placeholderAuditSelect)
	var dummy int32
	err := row.Scan(&dummy)
	return dummy, err
}
