// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaign_target_sites.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const deleteCampaignTargetSites = `-- name: DeleteCampaignTargetSites :exec
DELETE FROM campaign_target_sites
WHERE campaign_id = $1
`

func (q *Queries) DeleteCampaignTargetSites(ctx context.Context, campaignID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCampaignTargetSites, campaignID)
	return err
}

const insertCampaignTargetSite = `-- name: InsertCampaignTargetSite :exec

INSERT INTO campaign_target_sites (campaign_id, wp_site_id)
VALUES ($1, $2)
ON CONFLICT (campaign_id, wp_site_id) DO NOTHING
`

type InsertCampaignTargetSiteParams struct {
	CampaignID uuid.UUID `json:"campaign_id"`
	WpSiteID   uuid.UUID `json:"wp_site_id"`
}

// Queries for the campaign_target_sites join table.
// Maps which WP sites a campaign should post backlinks to.
// Normalized join table: campaign_id × wp_site_id (PK on both).
func (q *Queries) InsertCampaignTargetSite(ctx context.Context, arg InsertCampaignTargetSiteParams) error {
	_, err := q.db.Exec(ctx, insertCampaignTargetSite, arg.CampaignID, arg.WpSiteID)
	return err
}

const listCampaignTargetSites = `-- name: ListCampaignTargetSites :many
SELECT campaign_id, wp_site_id
FROM campaign_target_sites
WHERE campaign_id = $1
ORDER BY wp_site_id
`

func (q *Queries) ListCampaignTargetSites(ctx context.Context, campaignID uuid.UUID) ([]CampaignTargetSite, error) {
	rows, err := q.db.Query(ctx, listCampaignTargetSites, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignTargetSite
	for rows.Next() {
		var i CampaignTargetSite
		if err := rows.Scan(&i.CampaignID, &i.WpSiteID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWpSitesForCampaign = `-- name: ListWpSitesForCampaign :many
SELECT w.id, w.base_url, w.app_username, w.label, w.status
FROM wp_sites w
JOIN campaign_target_sites cts ON cts.wp_site_id = w.id
WHERE cts.campaign_id = $1
  AND w.deleted_at IS NULL
  AND w.status = 'connected'
ORDER BY w.created_at
`

type ListWpSitesForCampaignRow struct {
	ID          uuid.UUID    `json:"id"`
	BaseUrl     string       `json:"base_url"`
	AppUsername string       `json:"app_username"`
	Label       string       `json:"label"`
	Status      WpSiteStatus `json:"status"`
}

// Returns full WP site rows for a campaign's selected target sites.
// Used by JobService.Enqueue to resolve site URLs when building jobs.
func (q *Queries) ListWpSitesForCampaign(ctx context.Context, campaignID uuid.UUID) ([]ListWpSitesForCampaignRow, error) {
	rows, err := q.db.Query(ctx, listWpSitesForCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWpSitesForCampaignRow
	for rows.Next() {
		var i ListWpSitesForCampaignRow
		if err := rows.Scan(
			&i.ID,
			&i.BaseUrl,
			&i.AppUsername,
			&i.Label,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
