// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaigns.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const countRunningCampaignsByUser = `-- name: CountRunningCampaignsByUser :one
SELECT COUNT(*) FROM campaigns WHERE user_id = $1 AND status = 'running'
`

func (q *Queries) CountRunningCampaignsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRunningCampaignsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const placeholderCampaignsSelect = `-- name: PlaceholderCampaignsSelect :one

SELECT 1 AS dummy
`

// Queries for the campaigns table.
// Phase 2+ will add real queries here (create, list, pause, resume, archive).
// trg_campaign_limit trigger enforces max 3 running campaigns at DB layer.
// Placeholder kept so sqlc can parse this file without errors.
func (q *Queries) PlaceholderCampaignsSelect(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, placeholderCampaignsSelect)
	var dummy int32
	err := row.Scan(&dummy)
	return dummy, err
}
