// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaigns.sql

package sqlcdb

import (
	"context"
)

const placeholderCampaignsSelect = `-- name: PlaceholderCampaignsSelect :one

SELECT 1 AS dummy
`

// Queries for the campaigns table.
// Phase 2+ will add real queries here (create, list, pause, resume, archive).
// trg_campaign_limit trigger enforces max 3 running campaigns at DB layer.
// Placeholder kept so sqlc can parse this file without errors.
func (q *Queries) PlaceholderCampaignsSelect(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, placeholderCampaignsSelect)
	var dummy int32
	err := row.Scan(&dummy)
	return dummy, err
}
