// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package sqlcdb

import (
	"context"
)

const placeholderJobsSelect = `-- name: PlaceholderJobsSelect :one

SELECT 1 AS dummy
`

// Queries for the jobs table.
// Phase 2+ will add real queries here (enqueue, dispatch, complete, fail, stats).
// Placeholder kept so sqlc can parse this file without errors.
func (q *Queries) PlaceholderJobsSelect(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, placeholderJobsSelect)
	var dummy int32
	err := row.Scan(&dummy)
	return dummy, err
}
