// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs_content.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const getCampaignQueuedJobsForContent = `-- name: GetCampaignQueuedJobsForContent :many
SELECT
    j.id,
    j.anchor_text,
    j.anchor_type
FROM jobs j
JOIN campaigns c ON c.id = j.campaign_id
WHERE j.campaign_id = $1::uuid
  AND j.user_id     = $2::uuid
  AND j.status      = 'queued'
  AND j.content_body IS NULL
ORDER BY j.created_at ASC
`

type GetCampaignQueuedJobsForContentParams struct {
	CampaignID uuid.UUID `json:"campaign_id"`
	UserID     uuid.UUID `json:"user_id"`
}

type GetCampaignQueuedJobsForContentRow struct {
	ID         uuid.UUID `json:"id"`
	AnchorText string    `json:"anchor_text"`
	AnchorType string    `json:"anchor_type"`
}

// Returns queued jobs for a campaign that have no content yet.
// Used by ContentService to batch-generate articles.
func (q *Queries) GetCampaignQueuedJobsForContent(ctx context.Context, arg GetCampaignQueuedJobsForContentParams) ([]GetCampaignQueuedJobsForContentRow, error) {
	rows, err := q.db.Query(ctx, getCampaignQueuedJobsForContent, arg.CampaignID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCampaignQueuedJobsForContentRow
	for rows.Next() {
		var i GetCampaignQueuedJobsForContentRow
		if err := rows.Scan(&i.ID, &i.AnchorText, &i.AnchorType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobContent = `-- name: UpdateJobContent :exec

UPDATE jobs
SET
    content_body  = $1::text,
    content_title = $2::text,
    content_meta  = $3::text,
    status        = 'content_ready'
WHERE id      = $4::uuid
  AND user_id = $5::uuid
  AND status  = 'queued'
`

type UpdateJobContentParams struct {
	ContentBody  string    `json:"content_body"`
	ContentTitle string    `json:"content_title"`
	ContentMeta  string    `json:"content_meta"`
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
}

// Queries for AI content generation on jobs.
// These queries are separate from jobs.sql to keep the file size manageable.
// Transitions a queued job to content_ready after AI generation.
// Idempotent: only updates jobs still in queued status (skips already-processed).
func (q *Queries) UpdateJobContent(ctx context.Context, arg UpdateJobContentParams) error {
	_, err := q.db.Exec(ctx, updateJobContent,
		arg.ContentBody,
		arg.ContentTitle,
		arg.ContentMeta,
		arg.ID,
		arg.UserID,
	)
	return err
}
