// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const campaignJobStats = `-- name: CampaignJobStats :one
SELECT
    COUNT(*)::int AS total,
    COUNT(*) FILTER (WHERE status = 'queued')::int AS queued,
    COUNT(*) FILTER (WHERE status = 'dispatched')::int AS dispatched,
    COUNT(*) FILTER (WHERE status = 'in_progress')::int AS in_progress,
    COUNT(*) FILTER (WHERE status = 'success')::int AS success,
    COUNT(*) FILTER (WHERE status = 'failed')::int AS failed,
    COUNT(*) FILTER (WHERE status = 'skipped')::int AS skipped
FROM jobs
WHERE user_id = $1 AND campaign_id = $2
`

type CampaignJobStatsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	CampaignID uuid.UUID `json:"campaign_id"`
}

type CampaignJobStatsRow struct {
	Total      int32 `json:"total"`
	Queued     int32 `json:"queued"`
	Dispatched int32 `json:"dispatched"`
	InProgress int32 `json:"in_progress"`
	Success    int32 `json:"success"`
	Failed     int32 `json:"failed"`
	Skipped    int32 `json:"skipped"`
}

func (q *Queries) CampaignJobStats(ctx context.Context, arg CampaignJobStatsParams) (CampaignJobStatsRow, error) {
	row := q.db.QueryRow(ctx, campaignJobStats, arg.UserID, arg.CampaignID)
	var i CampaignJobStatsRow
	err := row.Scan(
		&i.Total,
		&i.Queued,
		&i.Dispatched,
		&i.InProgress,
		&i.Success,
		&i.Failed,
		&i.Skipped,
	)
	return i, err
}

const claimNextQueuedJob = `-- name: ClaimNextQueuedJob :one
WITH claimed AS (
    UPDATE jobs
    SET status = 'dispatched', dispatched_at = NOW()
    WHERE id = (
        SELECT j.id
        FROM jobs j
        JOIN campaigns c ON c.id = j.campaign_id
        WHERE j.user_id = $1
          AND j.status IN ('content_ready', 'queued')
          AND c.status = 'running'
        ORDER BY j.status DESC, j.created_at ASC
        LIMIT 1
        FOR UPDATE SKIP LOCKED
    )
    RETURNING id, user_id, campaign_id, target_id, target_url_snapshot, anchor_text, anchor_type, content_body, status, pool, credits_cost, captcha_cost, error_code, error_message, result_url, dispatched_at, completed_at, created_at, content_title, content_meta, lease_until, lease_holder, retry_count, last_error_at, verified, anchor_verified, verification_attempts, verified_at, verification_error, last_verification_at
)
SELECT claimed.id, claimed.user_id, claimed.campaign_id, claimed.target_id,
       claimed.target_url_snapshot, claimed.anchor_text, claimed.anchor_type,
       claimed.content_body, claimed.content_title, claimed.content_meta,
       claimed.status, claimed.pool, claimed.credits_cost,
       claimed.captcha_cost, claimed.error_code, claimed.error_message,
       claimed.result_url, claimed.dispatched_at, claimed.completed_at,
       claimed.created_at, c.money_site_url
FROM claimed
JOIN campaigns c ON c.id = claimed.campaign_id
`

type ClaimNextQueuedJobRow struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	CampaignID        uuid.UUID          `json:"campaign_id"`
	TargetID          *uuid.UUID         `json:"target_id"`
	TargetUrlSnapshot string             `json:"target_url_snapshot"`
	AnchorText        string             `json:"anchor_text"`
	AnchorType        string             `json:"anchor_type"`
	ContentBody       *string            `json:"content_body"`
	ContentTitle      *string            `json:"content_title"`
	ContentMeta       *string            `json:"content_meta"`
	Status            JobStatus          `json:"status"`
	Pool              string             `json:"pool"`
	CreditsCost       int32              `json:"credits_cost"`
	CaptchaCost       int32              `json:"captcha_cost"`
	ErrorCode         *string            `json:"error_code"`
	ErrorMessage      *string            `json:"error_message"`
	ResultUrl         *string            `json:"result_url"`
	DispatchedAt      pgtype.Timestamptz `json:"dispatched_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	CreatedAt         time.Time          `json:"created_at"`
	MoneySiteUrl      string             `json:"money_site_url"`
}

// Phase 7.04: claims content_ready jobs first (AI content populated), falling
// back to queued jobs (for backward compat when AI generation is disabled).
// Extension receives content_title / content_meta alongside content_body.
func (q *Queries) ClaimNextQueuedJob(ctx context.Context, userID uuid.UUID) (ClaimNextQueuedJobRow, error) {
	row := q.db.QueryRow(ctx, claimNextQueuedJob, userID)
	var i ClaimNextQueuedJobRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CampaignID,
		&i.TargetID,
		&i.TargetUrlSnapshot,
		&i.AnchorText,
		&i.AnchorType,
		&i.ContentBody,
		&i.ContentTitle,
		&i.ContentMeta,
		&i.Status,
		&i.Pool,
		&i.CreditsCost,
		&i.CaptchaCost,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ResultUrl,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.MoneySiteUrl,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :one
UPDATE jobs
SET status = 'success', result_url = $3, completed_at = NOW(), error_code = NULL, error_message = NULL
WHERE user_id = $1 AND id = $2 AND status IN ('dispatched', 'in_progress')
RETURNING id, user_id, campaign_id, target_id, target_url_snapshot, anchor_text, anchor_type, content_body, status, pool, credits_cost, captcha_cost, error_code, error_message, result_url, dispatched_at, completed_at, created_at, content_title, content_meta, lease_until, lease_holder, retry_count, last_error_at, verified, anchor_verified, verification_attempts, verified_at, verification_error, last_verification_at
`

type CompleteJobParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ID        uuid.UUID `json:"id"`
	ResultUrl *string   `json:"result_url"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, completeJob, arg.UserID, arg.ID, arg.ResultUrl)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CampaignID,
		&i.TargetID,
		&i.TargetUrlSnapshot,
		&i.AnchorText,
		&i.AnchorType,
		&i.ContentBody,
		&i.Status,
		&i.Pool,
		&i.CreditsCost,
		&i.CaptchaCost,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ResultUrl,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.ContentTitle,
		&i.ContentMeta,
		&i.LeaseUntil,
		&i.LeaseHolder,
		&i.RetryCount,
		&i.LastErrorAt,
		&i.Verified,
		&i.AnchorVerified,
		&i.VerificationAttempts,
		&i.VerifiedAt,
		&i.VerificationError,
		&i.LastVerificationAt,
	)
	return i, err
}

const countCampaignCompletedWork = `-- name: CountCampaignCompletedWork :one
SELECT COALESCE(SUM(credits_cost + captcha_cost), 0)::int
FROM jobs
WHERE user_id = $1
  AND campaign_id = $2
  AND status = 'success'
`

type CountCampaignCompletedWorkParams struct {
	UserID     uuid.UUID `json:"user_id"`
	CampaignID uuid.UUID `json:"campaign_id"`
}

func (q *Queries) CountCampaignCompletedWork(ctx context.Context, arg CountCampaignCompletedWorkParams) (int32, error) {
	row := q.db.QueryRow(ctx, countCampaignCompletedWork, arg.UserID, arg.CampaignID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countCampaignQueuedWork = `-- name: CountCampaignQueuedWork :one
SELECT COALESCE(SUM(credits_cost + captcha_cost), 0)::int
FROM jobs
WHERE user_id = $1
  AND campaign_id = $2
  AND status IN ('queued', 'dispatched', 'in_progress')
`

type CountCampaignQueuedWorkParams struct {
	UserID     uuid.UUID `json:"user_id"`
	CampaignID uuid.UUID `json:"campaign_id"`
}

func (q *Queries) CountCampaignQueuedWork(ctx context.Context, arg CountCampaignQueuedWorkParams) (int32, error) {
	row := q.db.QueryRow(ctx, countCampaignQueuedWork, arg.UserID, arg.CampaignID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createJob = `-- name: CreateJob :one

INSERT INTO jobs (
    user_id, campaign_id, target_id, target_url_snapshot, anchor_text,
    anchor_type, content_body, status, pool, credits_cost
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, 'queued', $8, $9
)
ON CONFLICT (campaign_id, target_id) WHERE target_id IS NOT NULL DO NOTHING
RETURNING id, user_id, campaign_id, target_id, target_url_snapshot, anchor_text, anchor_type, content_body, status, pool, credits_cost, captcha_cost, error_code, error_message, result_url, dispatched_at, completed_at, created_at, content_title, content_meta, lease_until, lease_holder, retry_count, last_error_at, verified, anchor_verified, verification_attempts, verified_at, verification_error, last_verification_at
`

type CreateJobParams struct {
	UserID            uuid.UUID  `json:"user_id"`
	CampaignID        uuid.UUID  `json:"campaign_id"`
	TargetID          *uuid.UUID `json:"target_id"`
	TargetUrlSnapshot string     `json:"target_url_snapshot"`
	AnchorText        string     `json:"anchor_text"`
	AnchorType        string     `json:"anchor_type"`
	ContentBody       *string    `json:"content_body"`
	Pool              string     `json:"pool"`
	CreditsCost       int32      `json:"credits_cost"`
}

// Queries for the jobs table.
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.UserID,
		arg.CampaignID,
		arg.TargetID,
		arg.TargetUrlSnapshot,
		arg.AnchorText,
		arg.AnchorType,
		arg.ContentBody,
		arg.Pool,
		arg.CreditsCost,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CampaignID,
		&i.TargetID,
		&i.TargetUrlSnapshot,
		&i.AnchorText,
		&i.AnchorType,
		&i.ContentBody,
		&i.Status,
		&i.Pool,
		&i.CreditsCost,
		&i.CaptchaCost,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ResultUrl,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.ContentTitle,
		&i.ContentMeta,
		&i.LeaseUntil,
		&i.LeaseHolder,
		&i.RetryCount,
		&i.LastErrorAt,
		&i.Verified,
		&i.AnchorVerified,
		&i.VerificationAttempts,
		&i.VerifiedAt,
		&i.VerificationError,
		&i.LastVerificationAt,
	)
	return i, err
}

const createJobForSite = `-- name: CreateJobForSite :one
INSERT INTO jobs (
    user_id, campaign_id, target_id, target_url_snapshot, anchor_text,
    anchor_type, status, pool, credits_cost
) VALUES (
    $1::uuid,
    $2::uuid,
    NULL,
    $3::text,
    $4::text,
    $5::text,
    'queued',
    $6::text,
    $7::int
)
ON CONFLICT (campaign_id, target_url_snapshot) WHERE target_id IS NULL DO NOTHING
RETURNING id, user_id, campaign_id, target_id, target_url_snapshot, anchor_text, anchor_type, content_body, status, pool, credits_cost, captcha_cost, error_code, error_message, result_url, dispatched_at, completed_at, created_at, content_title, content_meta, lease_until, lease_holder, retry_count, last_error_at, verified, anchor_verified, verification_attempts, verified_at, verification_error, last_verification_at
`

type CreateJobForSiteParams struct {
	UserID            uuid.UUID `json:"user_id"`
	CampaignID        uuid.UUID `json:"campaign_id"`
	TargetUrlSnapshot string    `json:"target_url_snapshot"`
	AnchorText        string    `json:"anchor_text"`
	AnchorType        string    `json:"anchor_type"`
	Pool              string    `json:"pool"`
	CreditsCost       int32     `json:"credits_cost"`
}

// Inserts a job sourced from a user's own wp_site (campaign_target_sites path).
// target_id is NULL because wp_sites are not rows in the targets table.
// Deduplication is enforced by the jobs_campaign_url_unique partial index
// (campaign_id, target_url_snapshot) WHERE target_id IS NULL.
func (q *Queries) CreateJobForSite(ctx context.Context, arg CreateJobForSiteParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJobForSite,
		arg.UserID,
		arg.CampaignID,
		arg.TargetUrlSnapshot,
		arg.AnchorText,
		arg.AnchorType,
		arg.Pool,
		arg.CreditsCost,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CampaignID,
		&i.TargetID,
		&i.TargetUrlSnapshot,
		&i.AnchorText,
		&i.AnchorType,
		&i.ContentBody,
		&i.Status,
		&i.Pool,
		&i.CreditsCost,
		&i.CaptchaCost,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ResultUrl,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.ContentTitle,
		&i.ContentMeta,
		&i.LeaseUntil,
		&i.LeaseHolder,
		&i.RetryCount,
		&i.LastErrorAt,
		&i.Verified,
		&i.AnchorVerified,
		&i.VerificationAttempts,
		&i.VerifiedAt,
		&i.VerificationError,
		&i.LastVerificationAt,
	)
	return i, err
}

const failJob = `-- name: FailJob :one
UPDATE jobs
SET status = 'failed', error_code = $3, error_message = $4, completed_at = NOW()
WHERE user_id = $1 AND id = $2 AND status IN ('queued', 'dispatched', 'in_progress')
RETURNING id, user_id, campaign_id, target_id, target_url_snapshot, anchor_text, anchor_type, content_body, status, pool, credits_cost, captcha_cost, error_code, error_message, result_url, dispatched_at, completed_at, created_at, content_title, content_meta, lease_until, lease_holder, retry_count, last_error_at, verified, anchor_verified, verification_attempts, verified_at, verification_error, last_verification_at
`

type FailJobParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ID           uuid.UUID `json:"id"`
	ErrorCode    *string   `json:"error_code"`
	ErrorMessage *string   `json:"error_message"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, failJob,
		arg.UserID,
		arg.ID,
		arg.ErrorCode,
		arg.ErrorMessage,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CampaignID,
		&i.TargetID,
		&i.TargetUrlSnapshot,
		&i.AnchorText,
		&i.AnchorType,
		&i.ContentBody,
		&i.Status,
		&i.Pool,
		&i.CreditsCost,
		&i.CaptchaCost,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ResultUrl,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.ContentTitle,
		&i.ContentMeta,
		&i.LeaseUntil,
		&i.LeaseHolder,
		&i.RetryCount,
		&i.LastErrorAt,
		&i.Verified,
		&i.AnchorVerified,
		&i.VerificationAttempts,
		&i.VerifiedAt,
		&i.VerificationError,
		&i.LastVerificationAt,
	)
	return i, err
}

const getJobByUser = `-- name: GetJobByUser :one
SELECT id, user_id, campaign_id, target_id, target_url_snapshot, anchor_text, anchor_type, content_body, status, pool, credits_cost, captcha_cost, error_code, error_message, result_url, dispatched_at, completed_at, created_at, content_title, content_meta, lease_until, lease_holder, retry_count, last_error_at, verified, anchor_verified, verification_attempts, verified_at, verification_error, last_verification_at FROM jobs
WHERE user_id = $1 AND id = $2
`

type GetJobByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetJobByUser(ctx context.Context, arg GetJobByUserParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByUser, arg.UserID, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CampaignID,
		&i.TargetID,
		&i.TargetUrlSnapshot,
		&i.AnchorText,
		&i.AnchorType,
		&i.ContentBody,
		&i.Status,
		&i.Pool,
		&i.CreditsCost,
		&i.CaptchaCost,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ResultUrl,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.ContentTitle,
		&i.ContentMeta,
		&i.LeaseUntil,
		&i.LeaseHolder,
		&i.RetryCount,
		&i.LastErrorAt,
		&i.Verified,
		&i.AnchorVerified,
		&i.VerificationAttempts,
		&i.VerifiedAt,
		&i.VerificationError,
		&i.LastVerificationAt,
	)
	return i, err
}

const getJobForReport = `-- name: GetJobForReport :one
SELECT id, user_id, campaign_id, target_id, target_url_snapshot, anchor_text, anchor_type, content_body, status, pool, credits_cost, captcha_cost, error_code, error_message, result_url, dispatched_at, completed_at, created_at, content_title, content_meta, lease_until, lease_holder, retry_count, last_error_at, verified, anchor_verified, verification_attempts, verified_at, verification_error, last_verification_at FROM jobs
WHERE user_id = $1
  AND id = $2
  AND status IN ('dispatched', 'in_progress')
FOR UPDATE
`

type GetJobForReportParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetJobForReport(ctx context.Context, arg GetJobForReportParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobForReport, arg.UserID, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CampaignID,
		&i.TargetID,
		&i.TargetUrlSnapshot,
		&i.AnchorText,
		&i.AnchorType,
		&i.ContentBody,
		&i.Status,
		&i.Pool,
		&i.CreditsCost,
		&i.CaptchaCost,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ResultUrl,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.ContentTitle,
		&i.ContentMeta,
		&i.LeaseUntil,
		&i.LeaseHolder,
		&i.RetryCount,
		&i.LastErrorAt,
		&i.Verified,
		&i.AnchorVerified,
		&i.VerificationAttempts,
		&i.VerifiedAt,
		&i.VerificationError,
		&i.LastVerificationAt,
	)
	return i, err
}

const listJobsByCampaign = `-- name: ListJobsByCampaign :many
SELECT id, user_id, campaign_id, target_id, target_url_snapshot, anchor_text, anchor_type, content_body, status, pool, credits_cost, captcha_cost, error_code, error_message, result_url, dispatched_at, completed_at, created_at, content_title, content_meta, lease_until, lease_holder, retry_count, last_error_at, verified, anchor_verified, verification_attempts, verified_at, verification_error, last_verification_at FROM jobs
WHERE user_id = $1 AND campaign_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListJobsByCampaignParams struct {
	UserID     uuid.UUID `json:"user_id"`
	CampaignID uuid.UUID `json:"campaign_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListJobsByCampaign(ctx context.Context, arg ListJobsByCampaignParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByCampaign,
		arg.UserID,
		arg.CampaignID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CampaignID,
			&i.TargetID,
			&i.TargetUrlSnapshot,
			&i.AnchorText,
			&i.AnchorType,
			&i.ContentBody,
			&i.Status,
			&i.Pool,
			&i.CreditsCost,
			&i.CaptchaCost,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.ResultUrl,
			&i.DispatchedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.ContentTitle,
			&i.ContentMeta,
			&i.LeaseUntil,
			&i.LeaseHolder,
			&i.RetryCount,
			&i.LastErrorAt,
			&i.Verified,
			&i.AnchorVerified,
			&i.VerificationAttempts,
			&i.VerifiedAt,
			&i.VerificationError,
			&i.LastVerificationAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobInProgress = `-- name: MarkJobInProgress :one
UPDATE jobs
SET status = 'in_progress'
WHERE user_id = $1 AND id = $2 AND status IN ('queued', 'dispatched')
RETURNING id, user_id, campaign_id, target_id, target_url_snapshot, anchor_text, anchor_type, content_body, status, pool, credits_cost, captcha_cost, error_code, error_message, result_url, dispatched_at, completed_at, created_at, content_title, content_meta, lease_until, lease_holder, retry_count, last_error_at, verified, anchor_verified, verification_attempts, verified_at, verification_error, last_verification_at
`

type MarkJobInProgressParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) MarkJobInProgress(ctx context.Context, arg MarkJobInProgressParams) (Job, error) {
	row := q.db.QueryRow(ctx, markJobInProgress, arg.UserID, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CampaignID,
		&i.TargetID,
		&i.TargetUrlSnapshot,
		&i.AnchorText,
		&i.AnchorType,
		&i.ContentBody,
		&i.Status,
		&i.Pool,
		&i.CreditsCost,
		&i.CaptchaCost,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ResultUrl,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.ContentTitle,
		&i.ContentMeta,
		&i.LeaseUntil,
		&i.LeaseHolder,
		&i.RetryCount,
		&i.LastErrorAt,
		&i.Verified,
		&i.AnchorVerified,
		&i.VerificationAttempts,
		&i.VerifiedAt,
		&i.VerificationError,
		&i.LastVerificationAt,
	)
	return i, err
}

const skipJob = `-- name: SkipJob :one
UPDATE jobs
SET status = 'skipped', error_code = $3, error_message = $4, completed_at = NOW()
WHERE user_id = $1 AND id = $2 AND status IN ('queued', 'dispatched', 'in_progress')
RETURNING id, user_id, campaign_id, target_id, target_url_snapshot, anchor_text, anchor_type, content_body, status, pool, credits_cost, captcha_cost, error_code, error_message, result_url, dispatched_at, completed_at, created_at, content_title, content_meta, lease_until, lease_holder, retry_count, last_error_at, verified, anchor_verified, verification_attempts, verified_at, verification_error, last_verification_at
`

type SkipJobParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ID           uuid.UUID `json:"id"`
	ErrorCode    *string   `json:"error_code"`
	ErrorMessage *string   `json:"error_message"`
}

func (q *Queries) SkipJob(ctx context.Context, arg SkipJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, skipJob,
		arg.UserID,
		arg.ID,
		arg.ErrorCode,
		arg.ErrorMessage,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CampaignID,
		&i.TargetID,
		&i.TargetUrlSnapshot,
		&i.AnchorText,
		&i.AnchorType,
		&i.ContentBody,
		&i.Status,
		&i.Pool,
		&i.CreditsCost,
		&i.CaptchaCost,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ResultUrl,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.ContentTitle,
		&i.ContentMeta,
		&i.LeaseUntil,
		&i.LeaseHolder,
		&i.RetryCount,
		&i.LastErrorAt,
		&i.Verified,
		&i.AnchorVerified,
		&i.VerificationAttempts,
		&i.VerifiedAt,
		&i.VerificationError,
		&i.LastVerificationAt,
	)
	return i, err
}
