// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs_verification.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const getJobForVerification = `-- name: GetJobForVerification :one
SELECT j.id, j.result_url, j.anchor_text, j.verification_attempts, c.money_site_url
FROM jobs j
JOIN campaigns c ON c.id = j.campaign_id
WHERE j.id = $1::uuid
  AND j.status = 'success'
`

type GetJobForVerificationRow struct {
	ID                   uuid.UUID `json:"id"`
	ResultUrl            *string   `json:"result_url"`
	AnchorText           string    `json:"anchor_text"`
	VerificationAttempts int32     `json:"verification_attempts"`
	MoneySiteUrl         string    `json:"money_site_url"`
}

// Fetches a single job's data needed by the verifier (result_url, money_site_url, anchor_text).
func (q *Queries) GetJobForVerification(ctx context.Context, jobID uuid.UUID) (GetJobForVerificationRow, error) {
	row := q.db.QueryRow(ctx, getJobForVerification, jobID)
	var i GetJobForVerificationRow
	err := row.Scan(
		&i.ID,
		&i.ResultUrl,
		&i.AnchorText,
		&i.VerificationAttempts,
		&i.MoneySiteUrl,
	)
	return i, err
}

const getUnverifiedJobs = `-- name: GetUnverifiedJobs :many
SELECT id, user_id, campaign_id, result_url, anchor_text, verification_attempts
FROM jobs
WHERE status = 'success'
  AND verified IS DISTINCT FROM TRUE
  AND verification_attempts < 3
  AND created_at < NOW() - INTERVAL '1 minute'
  AND (last_verification_at IS NULL OR last_verification_at < NOW() - INTERVAL '15 minutes')
ORDER BY created_at ASC
LIMIT $1::int
`

type GetUnverifiedJobsRow struct {
	ID                   uuid.UUID `json:"id"`
	UserID               uuid.UUID `json:"user_id"`
	CampaignID           uuid.UUID `json:"campaign_id"`
	ResultUrl            *string   `json:"result_url"`
	AnchorText           string    `json:"anchor_text"`
	VerificationAttempts int32     `json:"verification_attempts"`
}

// Returns success jobs that need verification or re-verification.
// Conditions:
//   - status = 'success' (only completed jobs are verified)
//   - verified IS DISTINCT FROM TRUE (not yet successfully verified)
//   - verification_attempts < 3 (under retry limit)
//   - created_at < NOW() - INTERVAL '1 minute' (debounce: allow DNS propagation)
//   - last_verification_at IS NULL OR last_verification_at < NOW() - INTERVAL '15 minutes'
//     (cooldown: don't hammer the same URL repeatedly)
func (q *Queries) GetUnverifiedJobs(ctx context.Context, limitCount int32) ([]GetUnverifiedJobsRow, error) {
	rows, err := q.db.Query(ctx, getUnverifiedJobs, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnverifiedJobsRow
	for rows.Next() {
		var i GetUnverifiedJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CampaignID,
			&i.ResultUrl,
			&i.AnchorText,
			&i.VerificationAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobVerified = `-- name: MarkJobVerified :exec

UPDATE jobs
SET verified              = $1::boolean,
    anchor_verified       = $2::boolean,
    verification_attempts = verification_attempts + 1,
    verified_at           = NOW(),
    last_verification_at  = NOW(),
    verification_error    = $3::text
WHERE id = $4::uuid
`

type MarkJobVerifiedParams struct {
	Verified          bool      `json:"verified"`
	AnchorVerified    bool      `json:"anchor_verified"`
	VerificationError string    `json:"verification_error"`
	JobID             uuid.UUID `json:"job_id"`
}

// Verification queries for post-publish checking.
// These are separate from jobs.sql to keep file sizes manageable.
// All queries target jobs with status='success' that need link verification.
// Updates verification result columns after a verification attempt.
// Increments verification_attempts and sets verified/anchor_verified/verified_at.
func (q *Queries) MarkJobVerified(ctx context.Context, arg MarkJobVerifiedParams) error {
	_, err := q.db.Exec(ctx, markJobVerified,
		arg.Verified,
		arg.AnchorVerified,
		arg.VerificationError,
		arg.JobID,
	)
	return err
}
