// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keys.sql

package sqlcdb

import (
	"context"
)

const placeholderKeysSelect = `-- name: PlaceholderKeysSelect :one

SELECT 1 AS dummy
`

// Queries for the api_keys table.
// Phase 2+ will add real queries here (key generation, revocation, lookup by hash).
// Placeholder kept so sqlc can parse this file without errors.
func (q *Queries) PlaceholderKeysSelect(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, placeholderKeysSelect)
	var dummy int32
	err := row.Scan(&dummy)
	return dummy, err
}
