// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package sqlcdb

import (
	"context"
)

const placeholderLedgerSelect = `-- name: PlaceholderLedgerSelect :one

SELECT 1 AS dummy
`

// Queries for the ledger table.
// Phase 2+ will add real queries here (history pagination, balance reconciliation).
// consume_credits / grant_credits are stored procs called via pool.Exec, not sqlc.
// Placeholder kept so sqlc can parse this file without errors.
func (q *Queries) PlaceholderLedgerSelect(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, placeholderLedgerSelect)
	var dummy int32
	err := row.Scan(&dummy)
	return dummy, err
}
