// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const countLedgerByUser = `-- name: CountLedgerByUser :one
SELECT COUNT(*) FROM ledger WHERE user_id = $1
`

func (q *Queries) CountLedgerByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLedgerByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLedgerConsumesByUser = `-- name: CountLedgerConsumesByUser :one
SELECT COUNT(*) FROM ledger
WHERE user_id = $1
  AND event_type IN ('consume_backlink', 'consume_captcha', 'consume_finder')
`

func (q *Queries) CountLedgerConsumesByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLedgerConsumesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLedgerConsumesByUserPage = `-- name: GetLedgerConsumesByUserPage :many
SELECT id, user_id, event_type, pool, delta_credits, balance_after, ref_entity_type, ref_entity_id, metadata, created_at FROM ledger
WHERE user_id = $1
  AND event_type IN ('consume_backlink', 'consume_captcha', 'consume_finder')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetLedgerConsumesByUserPageParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetLedgerConsumesByUserPage(ctx context.Context, arg GetLedgerConsumesByUserPageParams) ([]Ledger, error) {
	rows, err := q.db.Query(ctx, getLedgerConsumesByUserPage, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ledger
	for rows.Next() {
		var i Ledger
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.Pool,
			&i.DeltaCredits,
			&i.BalanceAfter,
			&i.RefEntityType,
			&i.RefEntityID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLedgerPage = `-- name: GetLedgerPage :many

SELECT id, user_id, event_type, pool, delta_credits, balance_after, ref_entity_type, ref_entity_id, metadata, created_at FROM ledger WHERE user_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type GetLedgerPageParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

// Queries for the ledger table. Phase 04: paginated history + count.
// grant_credits / consume_credits are stored procs called via tx.QueryRow, not sqlc.
func (q *Queries) GetLedgerPage(ctx context.Context, arg GetLedgerPageParams) ([]Ledger, error) {
	rows, err := q.db.Query(ctx, getLedgerPage, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ledger
	for rows.Next() {
		var i Ledger
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.Pool,
			&i.DeltaCredits,
			&i.BalanceAfter,
			&i.RefEntityType,
			&i.RefEntityID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
