// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CampaignStatus string

const (
	CampaignStatusDraft     CampaignStatus = "draft"
	CampaignStatusRunning   CampaignStatus = "running"
	CampaignStatusPaused    CampaignStatus = "paused"
	CampaignStatusCompleted CampaignStatus = "completed"
	CampaignStatusArchived  CampaignStatus = "archived"
)

func (e *CampaignStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CampaignStatus(s)
	case string:
		*e = CampaignStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CampaignStatus: %T", src)
	}
	return nil
}

type NullCampaignStatus struct {
	CampaignStatus CampaignStatus `json:"campaign_status"`
	Valid          bool           `json:"valid"` // Valid is true if CampaignStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCampaignStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CampaignStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CampaignStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCampaignStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CampaignStatus), nil
}

type JobStatus string

const (
	JobStatusQueued     JobStatus = "queued"
	JobStatusDispatched JobStatus = "dispatched"
	JobStatusInProgress JobStatus = "in_progress"
	JobStatusSuccess    JobStatus = "success"
	JobStatusFailed     JobStatus = "failed"
	JobStatusSkipped    JobStatus = "skipped"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type LedgerEventType string

const (
	LedgerEventTypeTrialGrant      LedgerEventType = "trial_grant"
	LedgerEventTypeTopup           LedgerEventType = "topup"
	LedgerEventTypeConsumeBacklink LedgerEventType = "consume_backlink"
	LedgerEventTypeConsumeCaptcha  LedgerEventType = "consume_captcha"
	LedgerEventTypeConsumeFinder   LedgerEventType = "consume_finder"
	LedgerEventTypeRefund          LedgerEventType = "refund"
	LedgerEventTypeAdminAdjust     LedgerEventType = "admin_adjust"
	LedgerEventTypeTopupExcess     LedgerEventType = "topup_excess"
)

func (e *LedgerEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerEventType(s)
	case string:
		*e = LedgerEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerEventType: %T", src)
	}
	return nil
}

type NullLedgerEventType struct {
	LedgerEventType LedgerEventType `json:"ledger_event_type"`
	Valid           bool            `json:"valid"` // Valid is true if LedgerEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerEventType) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerEventType), nil
}

type TargetSource string

const (
	TargetSourcePrebuilt TargetSource = "prebuilt"
	TargetSourceAutofind TargetSource = "autofind"
	TargetSourceCustom   TargetSource = "custom"
)

func (e *TargetSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TargetSource(s)
	case string:
		*e = TargetSource(s)
	default:
		return fmt.Errorf("unsupported scan type for TargetSource: %T", src)
	}
	return nil
}

type NullTargetSource struct {
	TargetSource TargetSource `json:"target_source"`
	Valid        bool         `json:"valid"` // Valid is true if TargetSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTargetSource) Scan(value interface{}) error {
	if value == nil {
		ns.TargetSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TargetSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTargetSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TargetSource), nil
}

type TargetType string

const (
	TargetTypeBlogComment      TargetType = "blog_comment"
	TargetTypeForumProfile     TargetType = "forum_profile"
	TargetTypeWeb2Post         TargetType = "web2_post"
	TargetTypeDirectoryListing TargetType = "directory_listing"
)

func (e *TargetType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TargetType(s)
	case string:
		*e = TargetType(s)
	default:
		return fmt.Errorf("unsupported scan type for TargetType: %T", src)
	}
	return nil
}

type NullTargetType struct {
	TargetType TargetType `json:"target_type"`
	Valid      bool       `json:"valid"` // Valid is true if TargetType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTargetType) Scan(value interface{}) error {
	if value == nil {
		ns.TargetType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TargetType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTargetType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TargetType), nil
}

type TransactionProvider string

const (
	TransactionProviderSepay        TransactionProvider = "sepay"
	TransactionProviderLemonsqueezy TransactionProvider = "lemonsqueezy"
	TransactionProviderManual       TransactionProvider = "manual"
)

func (e *TransactionProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionProvider(s)
	case string:
		*e = TransactionProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionProvider: %T", src)
	}
	return nil
}

type NullTransactionProvider struct {
	TransactionProvider TransactionProvider `json:"transaction_provider"`
	Valid               bool                `json:"valid"` // Valid is true if TransactionProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionProvider) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionProvider), nil
}

type TransactionStatus string

const (
	TransactionStatusPending                TransactionStatus = "pending"
	TransactionStatusPaid                   TransactionStatus = "paid"
	TransactionStatusFailed                 TransactionStatus = "failed"
	TransactionStatusRefunded               TransactionStatus = "refunded"
	TransactionStatusManualReview           TransactionStatus = "manual_review"
	TransactionStatusCancelled              TransactionStatus = "cancelled"
	TransactionStatusRecoveredByLatePayment TransactionStatus = "recovered_by_late_payment"
)

func (e *TransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatus(s)
	case string:
		*e = TransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatus: %T", src)
	}
	return nil
}

type NullTransactionStatus struct {
	TransactionStatus TransactionStatus `json:"transaction_status"`
	Valid             bool              `json:"valid"` // Valid is true if TransactionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatus), nil
}

type WpSiteStatus string

const (
	WpSiteStatusPending   WpSiteStatus = "pending"
	WpSiteStatusConnected WpSiteStatus = "connected"
	WpSiteStatusError     WpSiteStatus = "error"
)

func (e *WpSiteStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WpSiteStatus(s)
	case string:
		*e = WpSiteStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WpSiteStatus: %T", src)
	}
	return nil
}

type NullWpSiteStatus struct {
	WpSiteStatus WpSiteStatus `json:"wp_site_status"`
	Valid        bool         `json:"valid"` // Valid is true if WpSiteStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWpSiteStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WpSiteStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WpSiteStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWpSiteStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WpSiteStatus), nil
}

type ApiKey struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	KeyHash    []byte             `json:"key_hash"`
	KeyPrefix  string             `json:"key_prefix"`
	Name       *string            `json:"name"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  time.Time          `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type AuditLog struct {
	ID        int64      `json:"id"`
	UserID    *uuid.UUID `json:"user_id"`
	KeyID     *uuid.UUID `json:"key_id"`
	Event     string     `json:"event"`
	IpHash    []byte     `json:"ip_hash"`
	Country   *string    `json:"country"`
	Metadata  []byte     `json:"metadata"`
	CreatedAt time.Time  `json:"created_at"`
}

type Campaign struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	Name             string             `json:"name"`
	MoneySiteUrl     string             `json:"money_site_url"`
	NicheKeywords    []string           `json:"niche_keywords"`
	AnchorTexts      []byte             `json:"anchor_texts"`
	Pool             string             `json:"pool"`
	SourceMode       string             `json:"source_mode"`
	DailyLimit       int32              `json:"daily_limit"`
	Status           CampaignStatus     `json:"status"`
	EthicalMode      bool               `json:"ethical_mode"`
	NicheFilter      bool               `json:"niche_filter"`
	CreditsAllocated int32              `json:"credits_allocated"`
	CreditsConsumed  int32              `json:"credits_consumed"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

type DomainCooldown struct {
	UserID   uuid.UUID `json:"user_id"`
	Domain   string    `json:"domain"`
	LastUsed time.Time `json:"last_used"`
}

type DorkPattern struct {
	ID               int32          `json:"id"`
	Pattern          string         `json:"pattern"`
	TargetType       TargetType     `json:"target_type"`
	ExpectedPlatform *string        `json:"expected_platform"`
	SuccessWeight    pgtype.Numeric `json:"success_weight"`
	IsActive         bool           `json:"is_active"`
	CreatedAt        time.Time      `json:"created_at"`
}

type Job struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	CampaignID        uuid.UUID          `json:"campaign_id"`
	TargetID          uuid.UUID          `json:"target_id"`
	TargetUrlSnapshot string             `json:"target_url_snapshot"`
	AnchorText        string             `json:"anchor_text"`
	AnchorType        string             `json:"anchor_type"`
	ContentBody       *string            `json:"content_body"`
	Status            JobStatus          `json:"status"`
	Pool              string             `json:"pool"`
	CreditsCost       int32              `json:"credits_cost"`
	CaptchaCost       int32              `json:"captcha_cost"`
	ErrorCode         *string            `json:"error_code"`
	ErrorMessage      *string            `json:"error_message"`
	ResultUrl         *string            `json:"result_url"`
	DispatchedAt      pgtype.Timestamptz `json:"dispatched_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	CreatedAt         time.Time          `json:"created_at"`
}

type Ledger struct {
	ID            int64           `json:"id"`
	UserID        uuid.UUID       `json:"user_id"`
	EventType     LedgerEventType `json:"event_type"`
	Pool          string          `json:"pool"`
	DeltaCredits  int32           `json:"delta_credits"`
	BalanceAfter  int32           `json:"balance_after"`
	RefEntityType *string         `json:"ref_entity_type"`
	RefEntityID   *uuid.UUID      `json:"ref_entity_id"`
	Metadata      []byte          `json:"metadata"`
	CreatedAt     time.Time       `json:"created_at"`
}

type Referral struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	Code          string    `json:"code"`
	TotalReferred int32     `json:"total_referred"`
	CreatedAt     time.Time `json:"created_at"`
}

type SafeguardHit struct {
	ID        int64     `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Rule      string    `json:"rule"`
	Severity  string    `json:"severity"`
	Metadata  []byte    `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
}

type SupportTicket struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Subject    *string            `json:"subject"`
	Body       string             `json:"body"`
	Status     string             `json:"status"`
	CreatedAt  time.Time          `json:"created_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

type Target struct {
	ID             uuid.UUID          `json:"id"`
	Url            string             `json:"url"`
	Domain         string             `json:"domain"`
	Tld            *string            `json:"tld"`
	Type           TargetType         `json:"type"`
	Source         TargetSource       `json:"source"`
	OwnerUserID    *uuid.UUID         `json:"owner_user_id"`
	Pool           string             `json:"pool"`
	Dr             *int32             `json:"dr"`
	Da             *int32             `json:"da"`
	TrafficEst     *int32             `json:"traffic_est"`
	Language       *string            `json:"language"`
	NicheTags      []string           `json:"niche_tags"`
	Platform       *string            `json:"platform"`
	FormSelectors  []byte             `json:"form_selectors"`
	CaptchaType    *string            `json:"captcha_type"`
	CaptchaSitekey *string            `json:"captcha_sitekey"`
	IsActive       bool               `json:"is_active"`
	IsBlocklisted  bool               `json:"is_blocklisted"`
	SuccessRate    pgtype.Numeric     `json:"success_rate"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
	CreatedAt      time.Time          `json:"created_at"`
}

type Transaction struct {
	ID              uuid.UUID           `json:"id"`
	UserID          uuid.UUID           `json:"user_id"`
	Provider        TransactionProvider `json:"provider"`
	ProviderRef     *string             `json:"provider_ref"`
	PackageCode     string              `json:"package_code"`
	AmountVnd       int64               `json:"amount_vnd"`
	PremiumGranted  int32               `json:"premium_granted"`
	StandardGranted int32               `json:"standard_granted"`
	Status          TransactionStatus   `json:"status"`
	PaidAt          pgtype.Timestamptz  `json:"paid_at"`
	Metadata        []byte              `json:"metadata"`
	CreatedAt       time.Time           `json:"created_at"`
	UpdatedAt       time.Time           `json:"updated_at"`
}

type User struct {
	ID               uuid.UUID          `json:"id"`
	TelegramID       int64              `json:"telegram_id"`
	TelegramUsername *string            `json:"telegram_username"`
	PhoneE164        *string            `json:"phone_e164"`
	IsVerified       bool               `json:"is_verified"`
	IsBanned         bool               `json:"is_banned"`
	TrialUsed        bool               `json:"trial_used"`
	Language         string             `json:"language"`
	ReferredBy       *uuid.UUID         `json:"referred_by"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	LastActiveAt     pgtype.Timestamptz `json:"last_active_at"`
}

type VUserStat struct {
	ID              uuid.UUID `json:"id"`
	TelegramID      int64     `json:"telegram_id"`
	PremiumCredits  *int32    `json:"premium_credits"`
	StandardCredits *int32    `json:"standard_credits"`
	ActiveCampaigns int64     `json:"active_campaigns"`
	TotalBacklinks  int64     `json:"total_backlinks"`
	Backlinks24h    int64     `json:"backlinks_24h"`
}

type Wallet struct {
	UserID             uuid.UUID `json:"user_id"`
	PremiumCredits     int32     `json:"premium_credits"`
	StandardCredits    int32     `json:"standard_credits"`
	TotalPremiumSpent  int32     `json:"total_premium_spent"`
	TotalStandardSpent int32     `json:"total_standard_spent"`
	TotalVndSpent      int64     `json:"total_vnd_spent"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type WpSite struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	BaseUrl         string             `json:"base_url"`
	AppUsername     string             `json:"app_username"`
	AppPasswordEnc  []byte             `json:"app_password_enc"`
	Label           string             `json:"label"`
	Status          WpSiteStatus       `json:"status"`
	LastValidatedAt pgtype.Timestamptz `json:"last_validated_at"`
	LastError       *string            `json:"last_error"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}
