// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"context"
)

type Querier interface {
	// Queries for the audit_log and safeguard_hits tables.
	// Phase 2+ will add real queries here (event insert, anomaly lookup).
	// ip_hash stores sha256(ip) — raw IP is never persisted (see docs/threat-model.md Phase 7).
	// Placeholder kept so sqlc can parse this file without errors.
	PlaceholderAuditSelect(ctx context.Context) (int32, error)
	// Queries for the campaigns table.
	// Phase 2+ will add real queries here (create, list, pause, resume, archive).
	// trg_campaign_limit trigger enforces max 3 running campaigns at DB layer.
	// Placeholder kept so sqlc can parse this file without errors.
	PlaceholderCampaignsSelect(ctx context.Context) (int32, error)
	// Queries for the jobs table.
	// Phase 2+ will add real queries here (enqueue, dispatch, complete, fail, stats).
	// Placeholder kept so sqlc can parse this file without errors.
	PlaceholderJobsSelect(ctx context.Context) (int32, error)
	// Queries for the api_keys table.
	// Phase 2+ will add real queries here (key generation, revocation, lookup by hash).
	// Placeholder kept so sqlc can parse this file without errors.
	PlaceholderKeysSelect(ctx context.Context) (int32, error)
	// Queries for the ledger table.
	// Phase 2+ will add real queries here (history pagination, balance reconciliation).
	// consume_credits / grant_credits are stored procs called via pool.Exec, not sqlc.
	// Placeholder kept so sqlc can parse this file without errors.
	PlaceholderLedgerSelect(ctx context.Context) (int32, error)
	// Queries for the targets table.
	// Phase 2+ will add real queries here (pool fetch by type, domain cooldown check).
	// Note: {niche} in dork_patterns is a Go template placeholder, NOT SQL interpolation.
	// Placeholder kept so sqlc can parse this file without errors.
	PlaceholderTargetsSelect(ctx context.Context) (int32, error)
	// Queries for the users table.
	// Phase 2+ will add real queries here (Telegram bot /start, /me, referral lookup).
	// Placeholder kept so sqlc can parse this file without errors.
	PlaceholderUsersSelect(ctx context.Context) (int32, error)
	// Queries for the wallets table.
	// Phase 2+ will add real queries here (balance fetch, credit top-up via grant_credits proc).
	// Placeholder kept so sqlc can parse this file without errors.
	PlaceholderWalletsSelect(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
