// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddVNDSpent(ctx context.Context, arg AddVNDSpentParams) error
	CountLedgerByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	EnsureWallet(ctx context.Context, userID uuid.UUID) error
	// Queries for the api_keys table.
	// Phase 03: real queries replacing placeholder stub.
	// key_hash is BYTEA (SHA-256 of plaintext). Plaintext is NEVER stored.
	GetActiveKeyByUser(ctx context.Context, userID uuid.UUID) (ApiKey, error)
	GetKeyByHash(ctx context.Context, keyHash []byte) (ApiKey, error)
	// Queries for the ledger table. Phase 04: paginated history + count.
	// grant_credits / consume_credits are stored procs called via tx.QueryRow, not sqlc.
	GetLedgerPage(ctx context.Context, arg GetLedgerPageParams) ([]Ledger, error)
	// Queries for the users table.
	// Phase 02: real queries replacing placeholder stub.
	// NOTE: F4 trial-gate flow (SELECT FOR UPDATE + conditional UPDATE + grant_credits)
	//       is inlined as raw pgx.Tx in user_service.go — sqlc cannot model that compound
	//       transaction cleanly.
	GetUserByTelegramID(ctx context.Context, telegramID int64) (User, error)
	// Queries for the wallets table. Phase 04: balance fetch + VND spend bump.
	GetWalletByUser(ctx context.Context, userID uuid.UUID) (Wallet, error)
	InsertKey(ctx context.Context, arg InsertKeyParams) (ApiKey, error)
	// Queries for the audit_log and safeguard_hits tables.
	// Phase 2+ will add real queries here (event insert, anomaly lookup).
	// ip_hash stores sha256(ip) — raw IP is never persisted (see docs/threat-model.md Phase 7).
	// Placeholder kept so sqlc can parse this file without errors.
	PlaceholderAuditSelect(ctx context.Context) (int32, error)
	// Queries for the campaigns table.
	// Phase 2+ will add real queries here (create, list, pause, resume, archive).
	// trg_campaign_limit trigger enforces max 3 running campaigns at DB layer.
	// Placeholder kept so sqlc can parse this file without errors.
	PlaceholderCampaignsSelect(ctx context.Context) (int32, error)
	// Queries for the jobs table.
	// Phase 2+ will add real queries here (enqueue, dispatch, complete, fail, stats).
	// Placeholder kept so sqlc can parse this file without errors.
	PlaceholderJobsSelect(ctx context.Context) (int32, error)
	// Queries for the targets table.
	// Phase 2+ will add real queries here (pool fetch by type, domain cooldown check).
	// Note: {niche} in dork_patterns is a Go template placeholder, NOT SQL interpolation.
	// Placeholder kept so sqlc can parse this file without errors.
	PlaceholderTargetsSelect(ctx context.Context) (int32, error)
	RevokeActiveKeysForUser(ctx context.Context, userID uuid.UUID) error
	SetLanguage(ctx context.Context, arg SetLanguageParams) error
	SetPhoneAndVerify(ctx context.Context, arg SetPhoneAndVerifyParams) (User, error)
	UpsertUserStub(ctx context.Context, arg UpsertUserStubParams) (User, error)
}

var _ Querier = (*Queries)(nil)
