// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddVNDSpent(ctx context.Context, arg AddVNDSpentParams) error
	BanUser(ctx context.Context, telegramID int64) error
	BumpCampaignCreditsConsumed(ctx context.Context, arg BumpCampaignCreditsConsumedParams) error
	CampaignJobStats(ctx context.Context, arg CampaignJobStatsParams) (CampaignJobStatsRow, error)
	// [Q2] Sets status='cancelled' (NOT 'failed') so provider_ref stays in the
	// idx_tx_provider_ref_active partial index, enabling late-payment recovery in Phase 06.
	// Metadata is augmented (||) rather than replaced to preserve existing fields.
	CancelPendingTransaction(ctx context.Context, arg CancelPendingTransactionParams) error
	// Worker job queries for the embedded Go background worker (Phase 7.05).
	// These queries are separate from jobs.sql to keep file size manageable.
	// All claiming uses FOR UPDATE SKIP LOCKED for safe concurrent polling.
	// Claims a batch of content_ready jobs atomically, setting in_progress + lease.
	// Uses FOR UPDATE SKIP LOCKED so concurrent worker goroutines never double-claim.
	// sqlc.arg() with explicit ::type cast — lesson from Phase 7.02/7.03/7.04.
	ClaimContentReadyJobs(ctx context.Context, arg ClaimContentReadyJobsParams) ([]Job, error)
	// Phase 7.04: claims content_ready jobs first (AI content populated), falling
	// back to queued jobs (for backward compat when AI generation is disabled).
	// Extension receives content_title / content_meta alongside content_body.
	ClaimNextQueuedJob(ctx context.Context, userID uuid.UUID) (ClaimNextQueuedJobRow, error)
	CompleteJob(ctx context.Context, arg CompleteJobParams) (Job, error)
	CountActiveKeys(ctx context.Context) (int64, error)
	CountAuditLogByEventSince(ctx context.Context, arg CountAuditLogByEventSinceParams) (int64, error)
	CountCampaignCompletedWork(ctx context.Context, arg CountCampaignCompletedWorkParams) (int32, error)
	CountCampaignQueuedWork(ctx context.Context, arg CountCampaignQueuedWorkParams) (int32, error)
	// Returns the number of wp_sites linked to a campaign.
	// Used by JobService.Enqueue to decide between the new wp_sites path and legacy targets path.
	CountCampaignTargetSites(ctx context.Context, campaignID uuid.UUID) (int32, error)
	// Uses Asia/Ho_Chi_Minh timezone for month boundary (VN-only user base).
	// Avoids UTC drift where VN users see counter reset 7 hours early at month end.
	CountCreditsConsumedThisMonth(ctx context.Context, userID uuid.UUID) (int64, error)
	CountLedgerByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountLedgerConsumesByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountOpenTicketsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountRunningCampaignsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountTxByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	// Queries for admin dashboard stats. Phase 08: read-only aggregates used by AdminService.Stats.
	// All queries are point-in-time reads; no writes here.
	CountUsers(ctx context.Context) (int64, error)
	CountUsersBanned(ctx context.Context) (int64, error)
	CountUsersTrialUsed(ctx context.Context) (int64, error)
	CountUsersVerified(ctx context.Context) (int64, error)
	CountWpSitesByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	// Queries for the campaigns table.
	// trg_campaign_limit trigger enforces max 3 running campaigns at DB layer.
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error)
	// Queries for the targets table.
	// Note: {niche} in dork_patterns is a Go template placeholder, NOT SQL interpolation.
	CreateCustomTarget(ctx context.Context, arg CreateCustomTargetParams) (Target, error)
	// Queries for the jobs table.
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	// Inserts a job sourced from a user's own wp_site (campaign_target_sites path).
	// target_id is NULL because wp_sites are not rows in the targets table.
	// Deduplication is enforced by the jobs_campaign_url_unique partial index
	// (campaign_id, target_url_snapshot) WHERE target_id IS NULL.
	CreateJobForSite(ctx context.Context, arg CreateJobForSiteParams) (Job, error)
	CreditsOutstanding(ctx context.Context) (CreditsOutstandingRow, error)
	DeleteCampaignTargetSites(ctx context.Context, campaignID uuid.UUID) error
	EnsureWallet(ctx context.Context, userID uuid.UUID) error
	FailJob(ctx context.Context, arg FailJobParams) (Job, error)
	// Queries for the api_keys table.
	// Phase 03: real queries replacing placeholder stub.
	// key_hash is BYTEA (SHA-256 of plaintext). Plaintext is NEVER stored.
	GetActiveKeyByUser(ctx context.Context, userID uuid.UUID) (ApiKey, error)
	GetAuditLogByEventSince(ctx context.Context, arg GetAuditLogByEventSinceParams) ([]AuditLog, error)
	GetCampaignByUser(ctx context.Context, arg GetCampaignByUserParams) (Campaign, error)
	// Returns queued jobs for a campaign that have no content yet.
	// Used by ContentService to batch-generate articles.
	GetCampaignQueuedJobsForContent(ctx context.Context, arg GetCampaignQueuedJobsForContentParams) ([]GetCampaignQueuedJobsForContentRow, error)
	GetJobByUser(ctx context.Context, arg GetJobByUserParams) (Job, error)
	GetJobForReport(ctx context.Context, arg GetJobForReportParams) (Job, error)
	// Fetches a single job's data needed by the verifier (result_url, money_site_url, anchor_text).
	GetJobForVerification(ctx context.Context, jobID uuid.UUID) (GetJobForVerificationRow, error)
	GetKeyByHash(ctx context.Context, keyHash []byte) (ApiKey, error)
	GetLedgerConsumesByUserPage(ctx context.Context, arg GetLedgerConsumesByUserPageParams) ([]Ledger, error)
	// Queries for the ledger table. Phase 04: paginated history + count.
	// grant_credits / consume_credits are stored procs called via tx.QueryRow, not sqlc.
	GetLedgerPage(ctx context.Context, arg GetLedgerPageParams) ([]Ledger, error)
	// Returns the most-recent pending row for a user+package combination.
	// Used by CreateTopupIntent idempotent path when idx_tx_user_pkg_pending fires (23505).
	GetPendingTxByUserPackage(ctx context.Context, arg GetPendingTxByUserPackageParams) (Transaction, error)
	GetReferralByCode(ctx context.Context, code string) (Referral, error)
	// Queries for referrals table. Phase 07: code lookup + insert + increment.
	GetReferralByUser(ctx context.Context, userID uuid.UUID) (Referral, error)
	GetTargetForUser(ctx context.Context, arg GetTargetForUserParams) (Target, error)
	// Webhook lookup: find a transaction by its SePay order code (provider_ref).
	GetTxByProviderRef(ctx context.Context, providerRef *string) (Transaction, error)
	GetTxByUserPage(ctx context.Context, arg GetTxByUserPageParams) ([]Transaction, error)
	// Returns success jobs that need verification or re-verification.
	// Conditions:
	//   - status = 'success' (only completed jobs are verified)
	//   - verified IS DISTINCT FROM TRUE (not yet successfully verified)
	//   - verification_attempts < 3 (under retry limit)
	//   - created_at < NOW() - INTERVAL '1 minute' (debounce: allow DNS propagation)
	//   - last_verification_at IS NULL OR last_verification_at < NOW() - INTERVAL '15 minutes'
	//     (cooldown: don't hammer the same URL repeatedly)
	GetUnverifiedJobs(ctx context.Context, limitCount int32) ([]GetUnverifiedJobsRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByKeyPrefix(ctx context.Context, keyPrefix string) (User, error)
	GetUserByPhone(ctx context.Context, phoneE164 *string) (User, error)
	// Queries for the users table.
	// Phase 02: real queries replacing placeholder stub.
	// NOTE: F4 trial-gate flow (SELECT FOR UPDATE + conditional UPDATE + grant_credits)
	//       is inlined as raw pgx.Tx in user_service.go — sqlc cannot model that compound
	//       transaction cleanly.
	GetUserByTelegramID(ctx context.Context, telegramID int64) (User, error)
	// Used by extension endpoint /wp-sites/by-domain/:domain to fetch credentials for decryption.
	// Matches base_url containing the domain (ILIKE). Returns first match (LIMIT 1).
	// Status filter: active sites only (connected = validated successfully).
	GetWPSiteByUserDomain(ctx context.Context, arg GetWPSiteByUserDomainParams) (GetWPSiteByUserDomainRow, error)
	// Queries for the wallets table. Phase 04: balance fetch + VND spend bump.
	GetWalletByUser(ctx context.Context, userID uuid.UUID) (Wallet, error)
	// Returns queue depth, in-flight count, and last completed timestamp.
	// Used by GET /health/worker to expose worker state without exposing job data.
	GetWorkerHealth(ctx context.Context) (GetWorkerHealthRow, error)
	GetWpSiteByID(ctx context.Context, arg GetWpSiteByIDParams) (WpSite, error)
	// Bumps retry_count and records last failure details without changing status.
	// Called before RescheduleJobRetry or MoveJobToDLQ to record the failure.
	IncrementJobRetry(ctx context.Context, arg IncrementJobRetryParams) error
	IncrementReferralCount(ctx context.Context, userID uuid.UUID) error
	// Queries for the audit_log table. Phase 08: real event insert + lookup queries.
	// ip_hash stores sha256(ip) — raw IP is never persisted.
	// Phase 2 placeholder removed and replaced with real queries below.
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	// Queries for the campaign_target_sites join table.
	// Maps which WP sites a campaign should post backlinks to.
	// Normalized join table: campaign_id × wp_site_id (PK on both).
	InsertCampaignTargetSite(ctx context.Context, arg InsertCampaignTargetSiteParams) error
	InsertKey(ctx context.Context, arg InsertKeyParams) (ApiKey, error)
	// Queries for the transactions table. Phase 05: pending intent + cancel.
	// Phase 06 webhook will add MarkPaid / MarkRecovered queries.
	InsertPendingTransaction(ctx context.Context, arg InsertPendingTransactionParams) (Transaction, error)
	InsertReferral(ctx context.Context, arg InsertReferralParams) (Referral, error)
	// Queries for support_tickets table. Phase 07: ticket insert + open-count cap.
	InsertSupportTicket(ctx context.Context, arg InsertSupportTicketParams) (SupportTicket, error)
	// Queries for connected WordPress sites.
	InsertWpSite(ctx context.Context, arg InsertWpSiteParams) (WpSite, error)
	ListCampaignTargetSites(ctx context.Context, campaignID uuid.UUID) ([]CampaignTargetSite, error)
	ListCampaignsByUser(ctx context.Context, arg ListCampaignsByUserParams) ([]ListCampaignsByUserRow, error)
	ListJobsByCampaign(ctx context.Context, arg ListJobsByCampaignParams) ([]Job, error)
	ListTargetsForUser(ctx context.Context, arg ListTargetsForUserParams) ([]Target, error)
	ListWpSitesByUser(ctx context.Context, userID uuid.UUID) ([]ListWpSitesByUserRow, error)
	// Returns full WP site rows for a campaign's selected target sites.
	// Used by JobService.Enqueue to resolve site URLs when building jobs.
	ListWpSitesForCampaign(ctx context.Context, campaignID uuid.UUID) ([]ListWpSitesForCampaignRow, error)
	MarkJobInProgress(ctx context.Context, arg MarkJobInProgressParams) (Job, error)
	// Verification queries for post-publish checking.
	// These are separate from jobs.sql to keep file sizes manageable.
	// All queries target jobs with status='success' that need link verification.
	// Updates verification result columns after a verification attempt.
	// Increments verification_attempts and sets verified/anchor_verified/verified_at.
	MarkJobVerified(ctx context.Context, arg MarkJobVerifiedParams) error
	// Transitions a job to 'dlq' status after max retries exceeded.
	// Sets completed_at so it appears as a terminal state in duration metrics.
	MoveJobToDLQ(ctx context.Context, jobID uuid.UUID) error
	PickTargetsForCampaign(ctx context.Context, arg PickTargetsForCampaignParams) ([]Target, error)
	// Returns connected wp_sites linked to a campaign that do NOT already have a job
	// for this campaign (deduplication: one job per campaign×site URL pair).
	// Uses FOR UPDATE OF w SKIP LOCKED so concurrent Enqueue calls don't double-pick.
	PickWpSitesForCampaign(ctx context.Context, arg PickWpSitesForCampaignParams) ([]PickWpSitesForCampaignRow, error)
	// Re-queues a transiently-failed job as content_ready with a backoff lease_until.
	// The worker will not pick it up until lease_until has passed.
	RescheduleJobRetry(ctx context.Context, arg RescheduleJobRetryParams) error
	// Resolves a UUID prefix to up to 2 candidates for ambiguity check.
	// Bot uses 4-8 char prefixes; LIMIT 2 lets us detect collisions cheaply.
	ResolveCampaignIDPrefix(ctx context.Context, arg ResolveCampaignIDPrefixParams) ([]ResolveCampaignIDPrefixRow, error)
	RevokeActiveKeysForUser(ctx context.Context, userID uuid.UUID) error
	SetLanguage(ctx context.Context, arg SetLanguageParams) error
	SetPhoneAndVerify(ctx context.Context, arg SetPhoneAndVerifyParams) (User, error)
	SkipJob(ctx context.Context, arg SkipJobParams) (Job, error)
	SoftDeleteWpSite(ctx context.Context, arg SoftDeleteWpSiteParams) error
	TxStats24h(ctx context.Context) (TxStats24hRow, error)
	UnbanUser(ctx context.Context, telegramID int64) error
	UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error)
	// Queries for AI content generation on jobs.
	// These queries are separate from jobs.sql to keep the file size manageable.
	// Transitions a queued job to content_ready after AI generation.
	// Idempotent: only updates jobs still in queued status (skips already-processed).
	UpdateJobContent(ctx context.Context, arg UpdateJobContentParams) error
	UpdateWpSiteStatus(ctx context.Context, arg UpdateWpSiteStatusParams) error
	UpsertDomainCooldown(ctx context.Context, arg UpsertDomainCooldownParams) error
	UpsertUserStub(ctx context.Context, arg UpsertUserStubParams) (User, error)
}

var _ Querier = (*Queries)(nil)
