// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: referrals.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const getReferralByCode = `-- name: GetReferralByCode :one
SELECT id, user_id, code, total_referred, created_at FROM referrals WHERE code = $1
`

func (q *Queries) GetReferralByCode(ctx context.Context, code string) (Referral, error) {
	row := q.db.QueryRow(ctx, getReferralByCode, code)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.TotalReferred,
		&i.CreatedAt,
	)
	return i, err
}

const getReferralByUser = `-- name: GetReferralByUser :one

SELECT id, user_id, code, total_referred, created_at FROM referrals WHERE user_id = $1
`

// Queries for referrals table. Phase 07: code lookup + insert + increment.
func (q *Queries) GetReferralByUser(ctx context.Context, userID uuid.UUID) (Referral, error) {
	row := q.db.QueryRow(ctx, getReferralByUser, userID)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.TotalReferred,
		&i.CreatedAt,
	)
	return i, err
}

const incrementReferralCount = `-- name: IncrementReferralCount :exec
UPDATE referrals SET total_referred = total_referred + 1 WHERE user_id = $1
`

func (q *Queries) IncrementReferralCount(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementReferralCount, userID)
	return err
}

const insertReferral = `-- name: InsertReferral :one
INSERT INTO referrals (user_id, code) VALUES ($1, $2) RETURNING id, user_id, code, total_referred, created_at
`

type InsertReferralParams struct {
	UserID uuid.UUID `json:"user_id"`
	Code   string    `json:"code"`
}

func (q *Queries) InsertReferral(ctx context.Context, arg InsertReferralParams) (Referral, error) {
	row := q.db.QueryRow(ctx, insertReferral, arg.UserID, arg.Code)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.TotalReferred,
		&i.CreatedAt,
	)
	return i, err
}
