// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: support.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const countOpenTicketsByUser = `-- name: CountOpenTicketsByUser :one
SELECT COUNT(*) FROM support_tickets WHERE user_id = $1 AND status IN ('open','in_progress')
`

func (q *Queries) CountOpenTicketsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenTicketsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertSupportTicket = `-- name: InsertSupportTicket :one

INSERT INTO support_tickets (user_id, subject, body) VALUES ($1, $2, $3) RETURNING id, user_id, subject, body, status, created_at, resolved_at
`

type InsertSupportTicketParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Subject *string   `json:"subject"`
	Body    string    `json:"body"`
}

// Queries for support_tickets table. Phase 07: ticket insert + open-count cap.
func (q *Queries) InsertSupportTicket(ctx context.Context, arg InsertSupportTicketParams) (SupportTicket, error) {
	row := q.db.QueryRow(ctx, insertSupportTicket, arg.UserID, arg.Subject, arg.Body)
	var i SupportTicket
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
