// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: targets.sql

package sqlcdb

import (
	"context"
)

const placeholderTargetsSelect = `-- name: PlaceholderTargetsSelect :one

SELECT 1 AS dummy
`

// Queries for the targets table.
// Phase 2+ will add real queries here (pool fetch by type, domain cooldown check).
// Note: {niche} in dork_patterns is a Go template placeholder, NOT SQL interpolation.
// Placeholder kept so sqlc can parse this file without errors.
func (q *Queries) PlaceholderTargetsSelect(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, placeholderTargetsSelect)
	var dummy int32
	err := row.Scan(&dummy)
	return dummy, err
}
