// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const cancelPendingTransaction = `-- name: CancelPendingTransaction :exec
UPDATE transactions
SET status     = 'cancelled',
    updated_at = NOW(),
    metadata   = metadata || jsonb_build_object(
                     'cancel_reason', $2::text,
                     'cancelled_at',  to_char(NOW(), 'YYYY-MM-DD"T"HH24:MI:SSOF')
                 )
WHERE id = $1 AND status = 'pending'
`

type CancelPendingTransactionParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 string    `json:"column_2"`
}

// [Q2] Sets status='cancelled' (NOT 'failed') so provider_ref stays in the
// idx_tx_provider_ref_active partial index, enabling late-payment recovery in Phase 06.
// Metadata is augmented (||) rather than replaced to preserve existing fields.
func (q *Queries) CancelPendingTransaction(ctx context.Context, arg CancelPendingTransactionParams) error {
	_, err := q.db.Exec(ctx, cancelPendingTransaction, arg.ID, arg.Column2)
	return err
}

const countTxByUser = `-- name: CountTxByUser :one
SELECT COUNT(*) FROM transactions WHERE user_id = $1
`

func (q *Queries) CountTxByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTxByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPendingTxByUserPackage = `-- name: GetPendingTxByUserPackage :one
SELECT id, user_id, provider, provider_ref, package_code, amount_vnd, premium_granted, standard_granted, status, paid_at, metadata, created_at, updated_at FROM transactions
WHERE user_id = $1 AND package_code = $2 AND status = 'pending'
ORDER BY created_at DESC LIMIT 1
`

type GetPendingTxByUserPackageParams struct {
	UserID      uuid.UUID `json:"user_id"`
	PackageCode string    `json:"package_code"`
}

// Returns the most-recent pending row for a user+package combination.
// Used by CreateTopupIntent idempotent path when idx_tx_user_pkg_pending fires (23505).
func (q *Queries) GetPendingTxByUserPackage(ctx context.Context, arg GetPendingTxByUserPackageParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getPendingTxByUserPackage, arg.UserID, arg.PackageCode)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderRef,
		&i.PackageCode,
		&i.AmountVnd,
		&i.PremiumGranted,
		&i.StandardGranted,
		&i.Status,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTxByProviderRef = `-- name: GetTxByProviderRef :one
SELECT id, user_id, provider, provider_ref, package_code, amount_vnd, premium_granted, standard_granted, status, paid_at, metadata, created_at, updated_at FROM transactions WHERE provider = 'sepay' AND provider_ref = $1 LIMIT 1
`

// Webhook lookup: find a transaction by its SePay order code (provider_ref).
func (q *Queries) GetTxByProviderRef(ctx context.Context, providerRef *string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTxByProviderRef, providerRef)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderRef,
		&i.PackageCode,
		&i.AmountVnd,
		&i.PremiumGranted,
		&i.StandardGranted,
		&i.Status,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTxByUserPage = `-- name: GetTxByUserPage :many
SELECT id, user_id, provider, provider_ref, package_code, amount_vnd, premium_granted, standard_granted, status, paid_at, metadata, created_at, updated_at FROM transactions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetTxByUserPageParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetTxByUserPage(ctx context.Context, arg GetTxByUserPageParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTxByUserPage, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderRef,
			&i.PackageCode,
			&i.AmountVnd,
			&i.PremiumGranted,
			&i.StandardGranted,
			&i.Status,
			&i.PaidAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPendingTransaction = `-- name: InsertPendingTransaction :one

INSERT INTO transactions (user_id, provider, provider_ref, package_code, amount_vnd, premium_granted, standard_granted)
VALUES ($1, 'sepay', $2, $3, $4, $5, $6)
RETURNING id, user_id, provider, provider_ref, package_code, amount_vnd, premium_granted, standard_granted, status, paid_at, metadata, created_at, updated_at
`

type InsertPendingTransactionParams struct {
	UserID          uuid.UUID `json:"user_id"`
	ProviderRef     *string   `json:"provider_ref"`
	PackageCode     string    `json:"package_code"`
	AmountVnd       int64     `json:"amount_vnd"`
	PremiumGranted  int32     `json:"premium_granted"`
	StandardGranted int32     `json:"standard_granted"`
}

// Queries for the transactions table. Phase 05: pending intent + cancel.
// Phase 06 webhook will add MarkPaid / MarkRecovered queries.
func (q *Queries) InsertPendingTransaction(ctx context.Context, arg InsertPendingTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, insertPendingTransaction,
		arg.UserID,
		arg.ProviderRef,
		arg.PackageCode,
		arg.AmountVnd,
		arg.PremiumGranted,
		arg.StandardGranted,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderRef,
		&i.PackageCode,
		&i.AmountVnd,
		&i.PremiumGranted,
		&i.StandardGranted,
		&i.Status,
		&i.PaidAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
