// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const ensureWallet = `-- name: EnsureWallet :exec
INSERT INTO wallets (user_id) VALUES ($1) ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) EnsureWallet(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureWallet, userID)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, telegram_id, telegram_username, phone_e164, is_verified, is_banned, trial_used, language, referred_by, created_at, updated_at, last_active_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.PhoneE164,
		&i.IsVerified,
		&i.IsBanned,
		&i.TrialUsed,
		&i.Language,
		&i.ReferredBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const getUserByTelegramID = `-- name: GetUserByTelegramID :one

SELECT id, telegram_id, telegram_username, phone_e164, is_verified, is_banned, trial_used, language, referred_by, created_at, updated_at, last_active_at FROM users WHERE telegram_id = $1
`

// Queries for the users table.
// Phase 02: real queries replacing placeholder stub.
// NOTE: F4 trial-gate flow (SELECT FOR UPDATE + conditional UPDATE + grant_credits)
//
//	is inlined as raw pgx.Tx in user_service.go — sqlc cannot model that compound
//	transaction cleanly.
func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramID, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.PhoneE164,
		&i.IsVerified,
		&i.IsBanned,
		&i.TrialUsed,
		&i.Language,
		&i.ReferredBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const setLanguage = `-- name: SetLanguage :exec
UPDATE users SET language = $2, updated_at = NOW() WHERE id = $1
`

type SetLanguageParams struct {
	ID       uuid.UUID `json:"id"`
	Language string    `json:"language"`
}

func (q *Queries) SetLanguage(ctx context.Context, arg SetLanguageParams) error {
	_, err := q.db.Exec(ctx, setLanguage, arg.ID, arg.Language)
	return err
}

const setPhoneAndVerify = `-- name: SetPhoneAndVerify :one
UPDATE users
SET phone_e164  = $2,
    is_verified = TRUE,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, telegram_id, telegram_username, phone_e164, is_verified, is_banned, trial_used, language, referred_by, created_at, updated_at, last_active_at
`

type SetPhoneAndVerifyParams struct {
	ID        uuid.UUID `json:"id"`
	PhoneE164 *string   `json:"phone_e164"`
}

func (q *Queries) SetPhoneAndVerify(ctx context.Context, arg SetPhoneAndVerifyParams) (User, error) {
	row := q.db.QueryRow(ctx, setPhoneAndVerify, arg.ID, arg.PhoneE164)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.PhoneE164,
		&i.IsVerified,
		&i.IsBanned,
		&i.TrialUsed,
		&i.Language,
		&i.ReferredBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const upsertUserStub = `-- name: UpsertUserStub :one
INSERT INTO users (telegram_id, telegram_username, language)
VALUES ($1, $2, 'vi')
ON CONFLICT (telegram_id) DO UPDATE SET
    telegram_username = EXCLUDED.telegram_username,
    last_active_at    = NOW(),
    updated_at        = NOW()
RETURNING id, telegram_id, telegram_username, phone_e164, is_verified, is_banned, trial_used, language, referred_by, created_at, updated_at, last_active_at
`

type UpsertUserStubParams struct {
	TelegramID       int64   `json:"telegram_id"`
	TelegramUsername *string `json:"telegram_username"`
}

func (q *Queries) UpsertUserStub(ctx context.Context, arg UpsertUserStubParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserStub, arg.TelegramID, arg.TelegramUsername)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.TelegramUsername,
		&i.PhoneE164,
		&i.IsVerified,
		&i.IsBanned,
		&i.TrialUsed,
		&i.Language,
		&i.ReferredBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
	)
	return i, err
}
