// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcdb

import (
	"context"
)

const placeholderUsersSelect = `-- name: PlaceholderUsersSelect :one

SELECT 1 AS dummy
`

// Queries for the users table.
// Phase 2+ will add real queries here (Telegram bot /start, /me, referral lookup).
// Placeholder kept so sqlc can parse this file without errors.
func (q *Queries) PlaceholderUsersSelect(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, placeholderUsersSelect)
	var dummy int32
	err := row.Scan(&dummy)
	return dummy, err
}
