// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallets.sql

package sqlcdb

import (
	"context"
)

const placeholderWalletsSelect = `-- name: PlaceholderWalletsSelect :one

SELECT 1 AS dummy
`

// Queries for the wallets table.
// Phase 2+ will add real queries here (balance fetch, credit top-up via grant_credits proc).
// Placeholder kept so sqlc can parse this file without errors.
func (q *Queries) PlaceholderWalletsSelect(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, placeholderWalletsSelect)
	var dummy int32
	err := row.Scan(&dummy)
	return dummy, err
}
