// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const addVNDSpent = `-- name: AddVNDSpent :exec
UPDATE wallets SET total_vnd_spent = total_vnd_spent + $2, updated_at = NOW()
WHERE user_id = $1
`

type AddVNDSpentParams struct {
	UserID        uuid.UUID `json:"user_id"`
	TotalVndSpent int64     `json:"total_vnd_spent"`
}

func (q *Queries) AddVNDSpent(ctx context.Context, arg AddVNDSpentParams) error {
	_, err := q.db.Exec(ctx, addVNDSpent, arg.UserID, arg.TotalVndSpent)
	return err
}

const getWalletByUser = `-- name: GetWalletByUser :one

SELECT user_id, premium_credits, standard_credits, total_premium_spent, total_standard_spent, total_vnd_spent, updated_at FROM wallets WHERE user_id = $1
`

// Queries for the wallets table. Phase 04: balance fetch + VND spend bump.
func (q *Queries) GetWalletByUser(ctx context.Context, userID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByUser, userID)
	var i Wallet
	err := row.Scan(
		&i.UserID,
		&i.PremiumCredits,
		&i.StandardCredits,
		&i.TotalPremiumSpent,
		&i.TotalStandardSpent,
		&i.TotalVndSpent,
		&i.UpdatedAt,
	)
	return i, err
}
