// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker_jobs.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const claimContentReadyJobs = `-- name: ClaimContentReadyJobs :many

WITH claimed AS (
  SELECT id FROM jobs
  WHERE status = 'content_ready'
    AND (lease_until IS NULL OR lease_until < NOW())
  ORDER BY created_at ASC
  LIMIT $3::int
  FOR UPDATE SKIP LOCKED
)
UPDATE jobs
SET status      = 'in_progress',
    lease_until  = NOW() + ($1::int * INTERVAL '1 second'),
    lease_holder = $2::text
FROM claimed
WHERE jobs.id = claimed.id
RETURNING jobs.id, jobs.user_id, jobs.campaign_id, jobs.target_id, jobs.target_url_snapshot, jobs.anchor_text, jobs.anchor_type, jobs.content_body, jobs.status, jobs.pool, jobs.credits_cost, jobs.captcha_cost, jobs.error_code, jobs.error_message, jobs.result_url, jobs.dispatched_at, jobs.completed_at, jobs.created_at, jobs.content_title, jobs.content_meta, jobs.lease_until, jobs.lease_holder, jobs.retry_count, jobs.last_error_at
`

type ClaimContentReadyJobsParams struct {
	LeaseSeconds int32  `json:"lease_seconds"`
	LeaseHolder  string `json:"lease_holder"`
	LimitCount   int32  `json:"limit_count"`
}

// Worker job queries for the embedded Go background worker (Phase 7.05).
// These queries are separate from jobs.sql to keep file size manageable.
// All claiming uses FOR UPDATE SKIP LOCKED for safe concurrent polling.
// Claims a batch of content_ready jobs atomically, setting in_progress + lease.
// Uses FOR UPDATE SKIP LOCKED so concurrent worker goroutines never double-claim.
// sqlc.arg() with explicit ::type cast — lesson from Phase 7.02/7.03/7.04.
func (q *Queries) ClaimContentReadyJobs(ctx context.Context, arg ClaimContentReadyJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, claimContentReadyJobs, arg.LeaseSeconds, arg.LeaseHolder, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CampaignID,
			&i.TargetID,
			&i.TargetUrlSnapshot,
			&i.AnchorText,
			&i.AnchorType,
			&i.ContentBody,
			&i.Status,
			&i.Pool,
			&i.CreditsCost,
			&i.CaptchaCost,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.ResultUrl,
			&i.DispatchedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.ContentTitle,
			&i.ContentMeta,
			&i.LeaseUntil,
			&i.LeaseHolder,
			&i.RetryCount,
			&i.LastErrorAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkerHealth = `-- name: GetWorkerHealth :one
SELECT
    COUNT(*) FILTER (WHERE status = 'content_ready'
                       AND (lease_until IS NULL OR lease_until < NOW()))::int  AS queue_depth,
    COUNT(*) FILTER (WHERE status = 'in_progress')::int                        AS in_flight,
    COUNT(*) FILTER (WHERE status = 'success'
                       AND completed_at > NOW() - INTERVAL '5 minutes')::int   AS completed_last_5min,
    COUNT(*) FILTER (WHERE status IN ('failed','dlq')
                       AND completed_at > NOW() - INTERVAL '5 minutes')::int   AS failed_last_5min,
    MAX(completed_at) FILTER (WHERE status = 'success')                        AS last_completed_at
FROM jobs
`

type GetWorkerHealthRow struct {
	QueueDepth        int32       `json:"queue_depth"`
	InFlight          int32       `json:"in_flight"`
	CompletedLast5min int32       `json:"completed_last_5min"`
	FailedLast5min    int32       `json:"failed_last_5min"`
	LastCompletedAt   interface{} `json:"last_completed_at"`
}

// Returns queue depth, in-flight count, and last completed timestamp.
// Used by GET /health/worker to expose worker state without exposing job data.
func (q *Queries) GetWorkerHealth(ctx context.Context) (GetWorkerHealthRow, error) {
	row := q.db.QueryRow(ctx, getWorkerHealth)
	var i GetWorkerHealthRow
	err := row.Scan(
		&i.QueueDepth,
		&i.InFlight,
		&i.CompletedLast5min,
		&i.FailedLast5min,
		&i.LastCompletedAt,
	)
	return i, err
}

const incrementJobRetry = `-- name: IncrementJobRetry :exec
UPDATE jobs
SET retry_count   = retry_count + 1,
    last_error_at = NOW(),
    error_code    = $1::text,
    error_message = $2::text
WHERE id = $3::uuid
`

type IncrementJobRetryParams struct {
	ErrorCode    string    `json:"error_code"`
	ErrorMessage string    `json:"error_message"`
	JobID        uuid.UUID `json:"job_id"`
}

// Bumps retry_count and records last failure details without changing status.
// Called before RescheduleJobRetry or MoveJobToDLQ to record the failure.
func (q *Queries) IncrementJobRetry(ctx context.Context, arg IncrementJobRetryParams) error {
	_, err := q.db.Exec(ctx, incrementJobRetry, arg.ErrorCode, arg.ErrorMessage, arg.JobID)
	return err
}

const moveJobToDLQ = `-- name: MoveJobToDLQ :exec
UPDATE jobs
SET status       = 'dlq',
    completed_at = NOW()
WHERE id = $1::uuid
  AND status = 'in_progress'
`

// Transitions a job to 'dlq' status after max retries exceeded.
// Sets completed_at so it appears as a terminal state in duration metrics.
func (q *Queries) MoveJobToDLQ(ctx context.Context, jobID uuid.UUID) error {
	_, err := q.db.Exec(ctx, moveJobToDLQ, jobID)
	return err
}

const rescheduleJobRetry = `-- name: RescheduleJobRetry :exec
UPDATE jobs
SET status       = 'content_ready',
    lease_until  = NOW() + ($1::int * INTERVAL '1 second'),
    lease_holder = NULL
WHERE id = $2::uuid
  AND status = 'in_progress'
`

type RescheduleJobRetryParams struct {
	BackoffSeconds int32     `json:"backoff_seconds"`
	JobID          uuid.UUID `json:"job_id"`
}

// Re-queues a transiently-failed job as content_ready with a backoff lease_until.
// The worker will not pick it up until lease_until has passed.
func (q *Queries) RescheduleJobRetry(ctx context.Context, arg RescheduleJobRetryParams) error {
	_, err := q.db.Exec(ctx, rescheduleJobRetry, arg.BackoffSeconds, arg.JobID)
	return err
}
