// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wp_sites.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getWpSiteByID = `-- name: GetWpSiteByID :one
SELECT id, user_id, base_url, app_username, app_password_enc, label, status, last_validated_at, last_error, created_at, updated_at, deleted_at
FROM wp_sites
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
LIMIT 1
`

type GetWpSiteByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetWpSiteByID(ctx context.Context, arg GetWpSiteByIDParams) (WpSite, error) {
	row := q.db.QueryRow(ctx, getWpSiteByID, arg.ID, arg.UserID)
	var i WpSite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BaseUrl,
		&i.AppUsername,
		&i.AppPasswordEnc,
		&i.Label,
		&i.Status,
		&i.LastValidatedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertWpSite = `-- name: InsertWpSite :one

INSERT INTO wp_sites (user_id, base_url, app_username, app_password_enc, label, status, last_validated_at, last_error)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, base_url, app_username, app_password_enc, label, status, last_validated_at, last_error, created_at, updated_at, deleted_at
`

type InsertWpSiteParams struct {
	UserID          uuid.UUID          `json:"user_id"`
	BaseUrl         string             `json:"base_url"`
	AppUsername     string             `json:"app_username"`
	AppPasswordEnc  []byte             `json:"app_password_enc"`
	Label           string             `json:"label"`
	Status          WpSiteStatus       `json:"status"`
	LastValidatedAt pgtype.Timestamptz `json:"last_validated_at"`
	LastError       *string            `json:"last_error"`
}

// Queries for connected WordPress sites.
func (q *Queries) InsertWpSite(ctx context.Context, arg InsertWpSiteParams) (WpSite, error) {
	row := q.db.QueryRow(ctx, insertWpSite,
		arg.UserID,
		arg.BaseUrl,
		arg.AppUsername,
		arg.AppPasswordEnc,
		arg.Label,
		arg.Status,
		arg.LastValidatedAt,
		arg.LastError,
	)
	var i WpSite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BaseUrl,
		&i.AppUsername,
		&i.AppPasswordEnc,
		&i.Label,
		&i.Status,
		&i.LastValidatedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listWpSitesByUser = `-- name: ListWpSitesByUser :many
SELECT id, user_id, base_url, app_username, label, status, last_validated_at, last_error, created_at, updated_at
FROM wp_sites
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListWpSitesByUserRow struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	BaseUrl         string             `json:"base_url"`
	AppUsername     string             `json:"app_username"`
	Label           string             `json:"label"`
	Status          WpSiteStatus       `json:"status"`
	LastValidatedAt pgtype.Timestamptz `json:"last_validated_at"`
	LastError       *string            `json:"last_error"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) ListWpSitesByUser(ctx context.Context, userID uuid.UUID) ([]ListWpSitesByUserRow, error) {
	rows, err := q.db.Query(ctx, listWpSitesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWpSitesByUserRow
	for rows.Next() {
		var i ListWpSitesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BaseUrl,
			&i.AppUsername,
			&i.Label,
			&i.Status,
			&i.LastValidatedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWpSite = `-- name: SoftDeleteWpSite :exec
UPDATE wp_sites
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteWpSiteParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteWpSite(ctx context.Context, arg SoftDeleteWpSiteParams) error {
	_, err := q.db.Exec(ctx, softDeleteWpSite, arg.ID, arg.UserID)
	return err
}

const updateWpSiteStatus = `-- name: UpdateWpSiteStatus :exec
UPDATE wp_sites
SET status = $1, last_validated_at = NOW(), last_error = $2, updated_at = NOW()
WHERE id = $3 AND user_id = $4 AND deleted_at IS NULL
`

type UpdateWpSiteStatusParams struct {
	Status    WpSiteStatus `json:"status"`
	LastError *string      `json:"last_error"`
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
}

func (q *Queries) UpdateWpSiteStatus(ctx context.Context, arg UpdateWpSiteStatusParams) error {
	_, err := q.db.Exec(ctx, updateWpSiteStatus,
		arg.Status,
		arg.LastError,
		arg.ID,
		arg.UserID,
	)
	return err
}
