-- Phase 2 schema deltas: enum additions + provider_ref partial UNIQUE.
-- Fixes F2 (12-hex order code reuse across non-active states), Q1 (over-payment
-- bonus credits), Q2 (late-payment cancel recovery).

-- +goose Up
-- +goose NO TRANSACTION
-- Reason for NO TRANSACTION: ALTER TYPE ADD VALUE cannot run inside a txn block in Postgres.

-- Q1: new ledger event for bonus credits on over-payment
ALTER TYPE ledger_event_type ADD VALUE IF NOT EXISTS 'topup_excess';

-- Q2: new transaction statuses for late-payment recovery
ALTER TYPE transaction_status ADD VALUE IF NOT EXISTS 'cancelled';
ALTER TYPE transaction_status ADD VALUE IF NOT EXISTS 'recovered_by_late_payment';

-- F2: drop unconditional UNIQUE on provider_ref (constraint name auto-generated by 20260424001).
ALTER TABLE transactions DROP CONSTRAINT IF EXISTS transactions_provider_ref_key;

-- F2: partial UNIQUE limited to active states only. failed/refunded rows can share provider_ref with new attempts.
-- 'cancelled' is kept in the active set so a late webhook can transition to 'recovered_by_late_payment'.
CREATE UNIQUE INDEX IF NOT EXISTS idx_tx_provider_ref_active
  ON transactions(provider_ref)
  WHERE status IN ('pending','paid','cancelled','recovered_by_late_payment');

-- +goose Down
-- FORWARD-ONLY NOTE: Effectively forward-only due to partial index rebuild + enum value adds.
-- Rollback only reverts the provider_ref constraint; enum values persist (harmless when unused).
-- Full rollback (enum removal) requires destructive type recreate + data migration — not automated.

DROP INDEX IF EXISTS idx_tx_provider_ref_active;
-- Restore unconditional UNIQUE (may fail if duplicate provider_ref rows exist; accept manual cleanup).
ALTER TABLE transactions ADD CONSTRAINT transactions_provider_ref_key UNIQUE (provider_ref);
